(require '[print-manager.api :as api])
(api/start-server! :port 3000)


### Health Check
GET http://localhost:3000/api/health

### Autenticar Bambu
POST http://localhost:3000/api/auth/bambu
Content-Type: application/json

{
  "email": "isaacnewton.montinegro@gmail.com",
  "password": "Rising2003!"
}

### 2 - Confirmar com código
POST http://localhost:3000/api/auth/bambu
Content-Type: application/json

{
  "email": "isaacnewton.montinegro@gmail.com",
  "code": "047698"
}


### Ver status
GET http://localhost:3000/api/auth/status

### Listar filamentos
GET http://localhost:3000/api/filamentos

### Sincronizar impressão
POST http://localhost:3000/api/impressoes/sincronizar

### impressão
GET http://localhost:3000/api/impressoes

### impressão lucrativa
GET http://localhost:3000/api/impressoes/top-lucrativas

### Adicionar filamento PLA genérico
POST http://localhost:3000/api/filamentos
Content-Type: application/json

{
  "nome": "PLA Genérico",
  "marca": "Sem marca",
  "tipo": "PLA",
  "cor": "Variado",
  "peso-inicial-g": 1000,
  "preco-compra": 80.00
}

### Adicionar filamento PLA Preto Bambu
POST http://localhost:3000/api/filamentos
Content-Type: application/json

{
  "nome": "PLA Branco Bambu",
  "marca": "Bambu Lab",
  "tipo": "PLA",
  "cor": "Branco",
  "peso-inicial-g": 1000,
  "preco-compra": 99.90
}
